version: '3'

services:
  test:
    depends_on:
      - 'mongo-seed'
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    image: jwagner347/gift-app-api-unit
    environment:
       - DB_URL=mongodb://mongodb:27017/test

  mongodb:
    image: mongo:3
    container_name: mongodb

  mongo-seed:
    build: docker/mongo-seed
    depends_on:
      - mongodb
    links:
      - mongodb
