version: '3'

services:
  api:
   depends_on:
     - 'mongodb'
   build:
     context: .
     dockerfile: docker/test/api/Dockerfile
   image: jwagner347/gift-app-api-service-for-tests
   container_name: api
   volumes:
     - .:/usr/src/app
   environment:
      - DB_URL=mongodb://mongodb:27017/apitest
   ports:
     - '3000:3000'

  mongodb:
    image: mongo:3
    container_name: mongodb

  mongo-seed:
    build: docker/mongo-seed-api
    depends_on:
      - mongodb
    links:
      - mongodb
