version: 2
jobs:
  build:
    machine: true
      - image: circleci/classic:latest
    working_directory: ~/moonrise.works
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Unit Tests
          command: ./run_tests.sh unit

      - run:
          name: API Tests
          command: ./run_tests.sh api
